"""
Data models for the Expert Reasoning Engine.

These models define the structure for threat analysis, risk assessment,
and security recommendations generated by the AI reasoning engine.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from datetime import datetime
from enum import Enum


class ThreatSeverity(Enum):
    """Threat severity levels"""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class ThreatType(Enum):
    """Types of security threats"""
    MALWARE = "malware"
    INTRUSION = "intrusion"
    DATA_BREACH = "data_breach"
    INSIDER_THREAT = "insider_threat"
    PHISHING = "phishing"
    DDoS = "ddos"
    VULNERABILITY = "vulnerability"
    COMPLIANCE_VIOLATION = "compliance_violation"
    SUSPICIOUS_ACTIVITY = "suspicious_activity"
    CONFIGURATION_ISSUE = "configuration_issue"


class RiskLevel(Enum):
    """Risk assessment levels"""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass
class Evidence:
    """Evidence supporting a threat or finding"""
    source: str
    timestamp: datetime
    description: str
    raw_data: Dict[str, Any]
    confidence: float  # 0.0 to 1.0


@dataclass
class Pattern:
    """Security pattern identified in the data"""
    pattern_type: str
    description: str
    indicators: List[str]
    frequency: int
    confidence: float


@dataclass
class Event:
    """Security event in a timeline"""
    timestamp: datetime
    event_type: str
    description: str
    source: str
    severity: ThreatSeverity


@dataclass
class Threat:
    """Identified security threat"""
    threat_id: str
    threat_type: ThreatType
    severity: ThreatSeverity
    title: str
    description: str
    affected_systems: List[str]
    indicators: List[str]
    timeline: List[Event]
    evidence: List[Evidence]
    confidence: float  # 0.0 to 1.0
    mitigation_status: str = "open"
    first_seen: Optional[datetime] = None
    last_seen: Optional[datetime] = None


@dataclass
class Recommendation:
    """Security recommendation"""
    recommendation_id: str
    priority: str  # critical, high, medium, low
    category: str
    title: str
    description: str
    implementation_steps: List[str]
    estimated_effort: str  # hours, days, weeks
    business_impact: str
    cost_benefit_ratio: Optional[float] = None
    related_threats: List[str] = field(default_factory=list)
    compliance_frameworks: List[str] = field(default_factory=list)
    # Enhanced fields for detailed analysis
    cost_analysis: Optional[Dict[str, Any]] = None
    benefit_analysis: Optional[Dict[str, Any]] = None
    roi_analysis: Optional[Dict[str, Any]] = None


@dataclass
class RiskAssessment:
    """Overall risk assessment"""
    overall_risk_score: float  # 0.0 to 10.0
    risk_level: RiskLevel
    critical_threats: int
    high_threats: int
    medium_threats: int
    low_threats: int
    risk_factors: List[str]
    mitigation_coverage: float  # percentage of threats with mitigations
    trend: str  # improving, stable, deteriorating


@dataclass
class ThreatAnalysis:
    """Complete threat analysis result"""
    analysis_id: str
    timestamp: datetime
    threats_identified: List[Threat]
    risk_assessment: RiskAssessment
    patterns: List[Pattern]
    recommendations: List[Recommendation]
    confidence_level: float
    data_sources_analyzed: List[str]
    analysis_duration: float  # seconds
    model_used: str
    summary: str
    executive_summary: str